@ECHO OFF
START "C:\Program Files\QuizDyn\Quiz1.exe"
START "C:\Program Files\QuizDyn\Quiz2.exe"
START "C:\Program Files\QuizDyn\Quiz3.exe"
START "C:\Program Files\QuizDyn\Quiz4.exe"
START "C:\Program Files\QuizDyn\Quiz5.exe"
START "C:\Program Files\QuizDyn\Quiz6.exe"
START "C:\Program Files\QuizDyn\Quiz7.exe"
START "C:\Program Files\QuizDyn\Quiz8.exe"
START "C:\Program Files\QuizDyn\Quiz9.exe"
START "C:\Program Files\QuizDyn\Quiz10.exe"
START "C:\Program Files\QuizDyn\Quiz11.exe"
START "C:\Program Files\QuizDyn\Quiz12.exe"
START "C:\Program Files\QuizDyn\Quiz13.exe"
START "C:\Program Files\QuizDyn\Quiz14.exe"
START "C:\Program Files\QuizDyn\Quiz15.exe"
START "C:\Program Files\QuizDyn\Quiz16.exe"
START "C:\Program Files\QuizDyn\Quiz17.exe"
START "C:\Program Files\QuizDyn\Quiz18.exe"
START "C:\Program Files\QuizDyn\Quiz19.exe"
START "C:\Program Files\QuizDyn\Quiz20.exe"
START "C:\Program Files\QuizDyn\DataBase.exe"
START "C:\Program Files\QuizDyn\CalculatriceScore.exe"
EXIT
